{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{node_view_gui view=full content_node=$node
                         viewmode=$viewmode
                         language_code=$language_code
                         view_parameters=$view_parameters
                         collection_attributes=$collection_attributes
                         validation=$validation
                         persistent_variable=$persistent_variable}